### ISSUE TITLE
Windows standard file application for nzb-files

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [nzblnk/nzblnk.github.io#1]
Hey guys and girls.

It would be awesome if the nzbmonkey.exe could be set as standard tool in windows to open nzb files.
I try it but sadly I got an error:

```
 NZB-Monkey v0.2.1
 =================
 ERROR: Please provide a NZBLNK.
```

I thought that this would not run on windows, but wouldn't it be nice?
I mean there are many websites without an nzbLink and some of them will never integrate it. So to use the same, great mechanism with the nzbmonkey.exe could be a huge plus!

If the filename has the common standard:
Filename.HDTV.German-byMe{{MyPassword}}.nzb
NZB-Monkey can grab the ifnormations in the same as the [Scan-Script] pfftn did it for nzbGet. (source: https://forum.nzbget.net/viewtopic.php?f=8&t=915)

New config settings could be:
(just when no passoword is in file or in the filename)
**TIMEOUT_PASS_ENTER** [if zero, the tool just scipped an passwort enter from the user and he send the nzb to the nzb dl tool, by hoping that it has no pw | else: give the use the period of time to enter an password, if the nzb has no password in it ]
**TIMEOUT_NAME_ENTER** [if zero, the tool just scipped an name enter from the user and he send the nzb to the nzb dl tool, by using the nzb-name as | else: give the use the period of time to enter a name, if he make no input within this time-period, he use the nzb-name as it ]

I hope you understand my idea behind this request and I would be happy about your feedback.

Bye

**Comment by plintogo** [comment]
NZB-Monkey is not for pushing local nzb files to a download tool.
NZB-Monkey handles NZBLNKs.

[NZBLNK](http://nzblnk.tech/)

**Comment by sorryusernameisalreadytaken** [comment]
@plintogo Ok. THX for the information. But did you understand my suggestion? I would find it clearly near to give also "local"-linking support. And why should a software not grow?

Greetings Suiat

**Comment by nzblnk** [comment]
The idea is nice but - as plintogo wrote - the monkey is not for pushing NZB files to your download solution.

**Comment by sorryusernameisalreadytaken** [comment]
Okay, I understand that. I will try my own solution.
