### ISSUE TITLE
On the accuracy of the trademark symbol

### ISSUE THREAD

**Issue by mpldr** [nzblnk/nzblnk.github.io#16]
Hey, I've seen the trademark symbol being used on the website and was wondering whether this was accurate. I couldn't find it in any register I searched in.

**Comment by nzblnk** [comment]
Hi Moritz, please [see here](https://en.wikipedia.org/wiki/Unregistered_trademark). May I ask why you are interested in the trademark?

**Comment by mpldr** [comment]
I was honestly just curious if someone actually took time out of their day to officially register this as a trademark. Thanks for teaching me about the difference of registered vs. unregistered trademarks. :)
