### ISSUE TITLE
.NZB Files to NZBLNK?

### ISSUE THREAD

**Issue by Nou4r** [nzblnk/nzblnk.github.io#27]
I have around 200GB of NZB files and i'd like to convert them all into nzblnks, what would the most efficient way to do so?

Here is an example of two such files (copyright free):
[example.zip](https://github.com/nzblnk/nzblnk.github.io/files/12461318/example.zip)

**Comment by nzblnk** [comment]
I strongly advise against converting the NZBs into NZBLNKs. NZBLNKs are always dependent on search (engines). With the extended NZBLNK standard by the new parameter "upload time", one could possibly produce an NZB from an NZBLNK without search engines using the "NZB Monkey Go" tool. However, this is time-consuming considering the number of NZBs.

Regardless of this, the fastest way would be a script that looks into the NZBs and extracts the "header" from the FILE tags, looks up the password or extracts it from the file name. The "tag" is derived from the file name.
